### PR TITLE
Add a simple custom 404 page

### PR DESCRIPTION
**Pull request by R4356th**
### Resolves

Moves a step forward in resolving #67.

### Changes

Adds a very simple (and definitely non-impressive) custom 404 page, but should be enough for now, I guess.

### Test Coverage

A live sample can be found [here](https://r4356th.github.io/404.html).

### CODE REVIEW

**Comment by Daniel4-Scratch** [comment]
don't you need a file to redirect to the 404 tmp? Like a YAML file.

**Comment by R4356th** [comment]
Snap<i>!</i> devs will have to take care of that.

**Comment by Daniel4-Scratch** [comment]
Ok. Cause they could try yaml, but I’ll think it will bug out because the way the website works.
```Yml 
---
permalink: /404.html
---
```

**Comment by GrahamSH-LLK** [comment]
> Ok. Cause they could try yaml, but I’ll think it will bug out because the way the website works.
> 
> ```yaml
> ---
> permalink: /404.html
> ---
> ```

Uh, yeah! It doesn't work that way... This would require backend work on snap-cloud.

**Comment by Daniel4-Scratch** [comment]
Does that explain why Snap<em>!</em> didn't have a 404 page in the first time?

**Comment by cycomachead** [comment]
We're going to move to a new system soon, so I'll close this. Thanks, though!

**Pull request closed without merging**
